### ISSUE TITLE
Primary Key and Foreign Keys have to be integers for it to work. 

### ISSUE THREAD

**Issue by clj2567** [HDI-Project/SDV#117]
If my Primary Keys are not numerical , during CPA it throws an error saying str cannot be compared with int. I looked at it closer and I found out that it converts the primary key into numerical but it doesn’t convert the foreign key due to which it fails in comparison. After manually converting the strings in the Key columns , I could get it working.

**Comment by JDTheRipperPC** [comment]
Hi @clj2567 , thank you for reporting this issue.

We are working constantly working on improving SDV. We will start working on this issue as soon as possible. If you would like you can share your metadata and the dataset with us to speed up our development.

**Comment by clj2567** [comment]
I am using the dataset that is mentioned in the paper. https://www.kaggle.com/c/airbnb-recruiting-new-user-bookings/data

PFA the metadata file.
[meta_sample.txt](https://github.com/HDI-Project/SDV/files/3646929/meta_sample.txt)

**Comment by csala** [comment]
This has been resolved in #121
