### ISSUE TITLE
Time required for sample_all function? 

### ISSUE THREAD

**Issue by clj2567** [HDI-Project/SDV#118]
The sample_all function never really returns anything. It keeps running in a loop. Is there any solution for this? One instance it ran for 2 hours , still no output.

**Comment by JDTheRipperPC** [comment]
Thank you for reporting this @clj2567.

To be able to help you, we would need some additional information about the data and metadata you are trying to sample. Also, could you provide us a code snippet that are you using to sample?

**Comment by csala** [comment]
Hi @clj2567 

There is an error in the categorical values sampling implementation that provoked this behavior: the time it takes to sample increases exponentially with the number of categorical columns found in the dataset.

This fix for this has been covered in the [issue_120_compatibility_with_rdt_issue72](https://github.com/HDI-Project/SDV/tree/issue_120_compatibility_with_rdt_issue72) branch and will be released soon.

**Comment by clj2567** [comment]
Hi @csala ,

Thanks for the update. Is there any timeline around this?

**Comment by csala** [comment]
> Thanks for the update. Is there any timeline around this?

Yes. This will most likely be released this week.

**Comment by JDTheRipperPC** [comment]
This should have been fixed in PR #121
