### ISSUE TITLE
Integrate with faker library

### ISSUE THREAD

**Issue by kveerama** [HDI-Project/SDV#51]
Integrate with faker library for certain data types 

https://github.com/stympy/faker

**Comment by Aylr** [comment]
Another option worth considering is `mimesis` which is very similar to faker (a library I use and love), and much more performant. https://mimesis.readthedocs.io/foreword.html#advantages

**Comment by ManuelAlvarezC** [comment]
Hi @Aylr, and thanks for your suggestion.

We have decided that the integration with `faker` will be done in the scope of [RDT](https://github.com/HDI-Project/RDT) and it's implementation has already been done: https://github.com/HDI-Project/RDT/issues/71.

However, we take note of your suggestion and have opened an issue regarding that on RDT: https://github.com/HDI-Project/RDT/issues/80
