### ISSUE TITLE
Modeler parameter not being used (?)

### ISSUE THREAD

**Issue by echo66** [HDI-Project/SDV#68]
SDV version: 0.1.0
Python version: 3.6
Operating System: Fedora release 28 (Twenty Eight)

### Description

I was trying to use the univariate KDE. To do that, I tried to set the `distribution` parameter in `sdv.Modeler` constructor to `sdv.univariate.KDEUnivariate`. The fitted modeler still uses `sdv.univariate.GaussianUnivariate`.

### What I Did

I ran the following code: 

```python
import pandas as pd
import numpy as np

from copulas.univariate import KDEUnivariate
from copulas.univariate import GaussianUnivariate
from copulas.multivariate import VineCopula
from copulas.multivariate import GaussianMultivariate
from copulas.multivariate.tree import TreeTypes

from sdv import Sampler
from sdv import Modeler
from sdv import CSVDataLoader
from functools import partial


data_loader = CSVDataLoader('boston.json')
dn = data_loader.load_data()
dn.transform_data()
modeler = Modeler(dn, distribution=KDEUnivariate)
modeler.model_database()
sampler = Sampler(dn, modeler)
```

I checked the distribution for `TAX` feature and it follows, in the synthetic data, a gaussian distribution, while in the original data it wasn't gaussian. To check that, I looked into both the modeler and the following KDE plots:

![image](https://user-images.githubusercontent.com/778261/46805783-e0162380-cd5d-11e8-8724-95ede5bd85d9.png)

![image](https://user-images.githubusercontent.com/778261/46805803-f0c69980-cd5d-11e8-867f-43a89c8af659.png)

If you want to run the code, you can use the annexed CSV and JSON files.

[boston-data.zip](https://github.com/HDI-Project/SDV/files/2468989/boston-data.zip)

**Comment by ManuelAlvarezC** [comment]
Thanks for reporting @echo66. We will look at it soon.
